// GENERATED by scripts/make-story.mjs — edit story/story.json instead.
//
// The ten people who set the travel exam and stamp the passport. One per city,
// in route order, so CHAMPIONS[cityIndex] is the champion of that stop.

export interface Champion {
  cityId: string
  name: string
  /** Their trade, in Danish. Definite, lower case: "stenhuggeren". */
  titleDa: string
  titleEn: string
  /** Who they are, in a sentence or two. Shown on arrival and on the map. */
  blurbEn: string
  /** How they knew the grandmother. Small and specific. */
  knewHer: string
  greetingDa: string
  greetingEn: string
  /** Shown above the exam paper, in their voice. */
  examIntroEn: string
  passDa: string
  passEn: string
  failDa: string
  failEn: string
  farewellDa: string
  farewellEn: string
  motif: string
}

export const CHAMPIONS: readonly Champion[] = [
  {
    "cityId": "sonderborg",
    "name": "Rita Asmussen",
    "titleDa": "stenhuggeren",
    "titleEn": "stonemason",
    "blurbEn": "Rita Asmussen cuts letters into granite in a yard on the Dybbøl road — headstones mostly, and the odd 1920 reunification stone gone green under the lichen. Half the families want the name in Danish and half want it in German, and she will not start the first letter until they have agreed; one family took her fourteen months.",
    "knewHer": "In 2004 she had a Polish surname to cut and nobody in Sønderjylland could tell her where the accents went, so she wrote to an address she was given; Ingeborg sent back the spelling, and a correction to the birth date nobody had asked about, and was right about both.",
    "greetingDa": "Så du er Ingeborgs barnebarn. Sæt dig ned — her går vi langsomt frem, og vi staver rigtigt.",
    "greetingEn": "So you're Ingeborg's grandchild. Sit down — we go slowly here, and we spell things right.",
    "examIntroEn": "Write them the way I cut them: once, and right.",
    "passDa": "Rent arbejde. Nu kan det stå ude i vejret.",
    "passEn": "Clean work. Now it can stand outside in the weather.",
    "failDa": "Det var ikke godt nok i dag, men ordene bliver ikke væk.",
    "failEn": "Not good enough today, but the words aren't going anywhere.",
    "farewellDa": "Hils manden i Ribe, og lån ham ikke penge.",
    "farewellEn": "Give the man in Ribe my regards, and don't lend him money.",
    "motif": "🔨"
  },
  {
    "cityId": "ribe",
    "name": "Verner Bak",
    "titleDa": "skorstensfejeren",
    "titleEn": "chimney sweep",
    "blurbEn": "Verner Bak has swept the chimneys of the old town for thirty-one years, so he has stood on every roof in Ribe, including the ones the storks have taken. Every spring the town bets on the day the first stork lands, and every spring Verner wins; he does not call this cheating, since nobody else bothers to look at the nests in February.",
    "knewHer": "She stopped at the foot of his ladder in April 1994 to settle a bet on when the first stork would land, lost it by two days, and posted a card promising two hundred kroner in person — the only debt he ever knew her to leave standing.",
    "greetingDa": "Nowak skylder mig to hundrede kroner. Du skal ikke betale dem — jeg vil hellere have dem af hende.",
    "greetingEn": "Nowak owes me two hundred kroner. You're not to pay them — I'd rather have them from her.",
    "examIntroEn": "I'll count these straight — there's no dealing yourself a better word.",
    "passDa": "Ikke en plet på den. Hold passet stille.",
    "passEn": "Not a mark on it. Hold the passport still.",
    "failDa": "Du tabte ærligt — det er også noget værd.",
    "failEn": "You lost honestly — that's worth something too.",
    "farewellDa": "Sig til hende, at jeg stadig venter — og at renterne løber.",
    "farewellEn": "Tell her I'm still waiting — and that the interest is running.",
    "motif": "🧹"
  },
  {
    "cityId": "kolding",
    "name": "Jette Krogh",
    "titleDa": "værkstedslederen",
    "titleEn": "workshop manager",
    "blurbEn": "Jette Krogh runs the model workshop at the design school, and before that she spent eight years as a joiner on the Koldinghus rebuild, setting new oak against brick the 1808 fire had cooked black. She will not let a student sand a join smooth — the join is the part that tells you what happened.",
    "knewHer": "Ingeborg interpreted for a German delegation on Jette's scaffolding for two days in 1989, working from a card index she carried in a shoebox — one card per term, ruled and dated, in every language she had. She asked Jette to say limtræ six times, and did not write it down.",
    "greetingDa": "Her reparerer vi tingene, men vi skjuler ikke, hvor de gik i stykker.",
    "greetingEn": "We repair things here, but we don't hide where they broke.",
    "examIntroEn": "No clean copies. What you get wrong stays on the paper, where we can both look at it.",
    "passDa": "Der er ikke noget at rette. Jeg henter stemplet — det bruger jeg sjældnere end blyanten.",
    "passEn": "Nothing to correct. I'll get the stamp — I use it less often than the pencil.",
    "failDa": "Fejlen bliver stående, men nu ved du, hvor den er.",
    "failEn": "The fault stays standing, but now you know where it is.",
    "farewellDa": "Nordpå, så. Og lad være med at slibe det glat.",
    "farewellEn": "North, then. And don't sand it smooth.",
    "motif": "🪚"
  },
  {
    "cityId": "aarhus",
    "name": "Vibeke Kjærgaard",
    "titleDa": "tonemesteren",
    "titleEn": "sound engineer",
    "blurbEn": "Vibeke Kjærgaard mixes sound at Musikhuset and has wired the interpreter booths for nearly every large conference Aarhus has hosted since the eighties. She holds that this city apologises for its own accent far too often, and that a word said loudly and wrongly carries further than a word said correctly under your breath.",
    "knewHer": "She ran the audio at a three-day fisheries conference in 1994, where Ingeborg worked booth four and was the only interpreter who ever asked her to repair the cough button instead of complaining about it afterwards; Vibeke also noticed that during the Danish session, the one hour with no channel for her, Ingeborg kept her headphones on and skipped lunch.",
    "greetingDa": "Nu er du nordpå. Her lyder ordene lidt anderledes, men de betyder det samme.",
    "greetingEn": "You're up north now. The words sound a little different here, but they mean the same thing.",
    "examIntroEn": "Say them out loud if it helps — I have heard far worse Danish than yours come through far better headphones.",
    "passDa": "Nu er der ikke mere støj på linjen.",
    "passEn": "Now there's no more noise on the line.",
    "failDa": "Du hørte dem, men du fangede dem ikke.",
    "failEn": "You heard them, but you didn't catch them.",
    "farewellDa": "Tag ordene med, og sig dem højt undervejs.",
    "farewellEn": "Take the words with you, and say them out loud on the road.",
    "motif": "🎧"
  },
  {
    "cityId": "viborg",
    "name": "Thorkild Damsgaard",
    "titleDa": "retstolken",
    "titleEn": "court interpreter",
    "blurbEn": "Thorkild Damsgaard interprets at Vestre Landsret, the high court for all of Jutland — German and Polish, three days most weeks, since 1978. His view of conference interpreting, which is the work your grandmother did, is that nobody in the booth ever has to watch the consequence walk out of the room.",
    "knewHer": "She passed through Viborg once, in October 1981, hired for a congress, and beat him at ClueCabulary in the hour between sessions — nineteen minutes, and one clue he still insists was illegal. He has been drafting the letter that says so ever since.",
    "greetingDa": "Du behøver ikke fortælle mig, at hun har nævnt 1981. Det gør hun altid.",
    "greetingEn": "You don't need to tell me she mentioned 1981. She always does.",
    "examIntroEn": "In the room where I work, a word that is nearly right is a wrong word, and somebody else serves the difference.",
    "passDa": "Det er rigtigt, ord for ord. Jeg har ingen indsigelser.",
    "passEn": "That is right, word for word. I have no objections.",
    "failDa": "Forkert er forkert, men her koster det kun tid.",
    "failEn": "Wrong is wrong — but here it only costs time.",
    "farewellDa": "Brevet er stadig ikke sendt. Det må du gerne fortælle hende.",
    "farewellEn": "The letter still hasn't been sent. You're welcome to tell her that.",
    "motif": "⚖️"
  },
  {
    "cityId": "aalborg",
    "name": "Grethe Thomsen",
    "titleDa": "laboranten i Rørdal",
    "titleEn": "lab technician at Rørdal",
    "blurbEn": "Grethe Thomsen runs the laboratory at the cement works out at Rørdal, east along the fjord, where she pulls three samples a shift and fails the ones that only hold in good conditions. She has no patience for collecting words: a word is yours the first time it holds under load, not the first time you write it down.",
    "knewHer": "Ingeborg interpreted a plant tour here in 1987 and posted thirty-nine Danish words back to the laboratory afterwards for the spelling to be checked; Grethe confirmed all thirty-nine, though kalkslør she had invented on the tour herself rather than admit she had forgotten the real word for the dust. Ingeborg came out to the works once more, in 1998, on her own money and for no conference at all, and stood an hour at the kiln.",
    "greetingDa": "Otte kilometer ud ad fjorden for et stempel. Her tæller et ord først, når du har brugt det.",
    "greetingEn": "Eight kilometres out along the fjord for a stamp. A word doesn't count here until you have used it.",
    "examIntroEn": "We don't test concrete the day it is poured. We test it at twenty-eight days, when it is supposed to carry something. You have had these words a good while now.",
    "passDa": "Nu har du brugt dem, og så tæller de.",
    "passEn": "Now you have used them, so they count.",
    "failDa": "Prøven holdt ikke, og så laver vi den om.",
    "failEn": "The sample didn't hold, so we run it again.",
    "farewellDa": "To gange kom hun hertil, og begge gange rejste hun sydpå igen.",
    "farewellEn": "She came this far twice, and both times she went back south.",
    "motif": "🏭"
  },
  {
    "cityId": "skagen",
    "name": "Ellen Thorup",
    "titleDa": "ringmærkeren",
    "titleEn": "bird ringer",
    "blurbEn": "Ellen Thorup has ringed migrating birds at the station out on Grenen since 1993, and she is there most mornings an hour before light, counting what comes over. The painters came to Skagen for the light; she says they should have come for the wind, which is the thing that actually decides anything up here.",
    "knewHer": "In 1994 Ingeborg wrote to the station from a ship in the Kattegat to ask what the big white diving bird was called in Danish, corrected Ellen's English in the thank-you note that followed, and went on writing for thirty-two years without ever coming north to meet her.",
    "greetingDa": "Du kalder hende farmor. Jeg har kaldt hende fru Nowak i 32 år.",
    "greetingEn": "You call her Farmor. I have called her Fru Nowak for thirty-two years.",
    "examIntroEn": "I count what actually goes past, not what I was hoping for.",
    "passDa": "Der var ikke en eneste fejl, og nu står du i bogen.",
    "passEn": "Not a single mistake, and now you are in the book.",
    "failDa": "Jeg noterer kun det, der er rigtigt, og i dag var der for mange fejl.",
    "failEn": "I note down only what is right, and today there were too many mistakes.",
    "farewellDa": "Nu skal du sydpå, ligesom fuglene. Jeg skriver til hende i aften.",
    "farewellEn": "Now you go south, the same as the birds. I will write to her tonight.",
    "motif": "🐦"
  },
  {
    "cityId": "odense",
    "name": "Solvejg Riis",
    "titleDa": "nattevagten",
    "titleEn": "night nurse",
    "blurbEn": "Solvejg Riis has worked nights on the medical ward at Odense University Hospital since 1991, where the corridor goes quiet after two and people say things they would not say in daylight. She grew up three streets from the Andersen house, and holds that of all the people who have queued outside it, not one has noticed that the duckling story is about leaving.",
    "knewHer": "In the winter of 1997 a Polish deckhand came in off a ship with no Danish and no English, and the ward rang round until it found an interpreter in Copenhagen; Nowak took the last train the same evening and worked two nights at his bed, Polish to English and back. At six on the second morning she handed him to a Danish colleague for the ward round, because the round was in Danish and she could not follow it.",
    "greetingDa": "Du har været længe undervejs. Det kan man se på folk om natten.",
    "greetingEn": "You've been on the road a long time. At night you can see it on people.",
    "examIntroEn": "On a night shift you either know the word or you wake somebody up to ask — and there is nobody here for you to wake.",
    "passDa": "Du var rolig hele natten. Det er det bedste, jeg kan skrive i rapporten.",
    "passEn": "You stayed calm the whole night. That is the best thing I can write in a report.",
    "failDa": "Ikke i nat. Vi tager den igen i morgen.",
    "failEn": "Not tonight. We'll take it again tomorrow.",
    "farewellDa": "Andersen gik herfra, da han var fjorten — du skal bare nå toget.",
    "farewellEn": "Andersen left here on foot at fourteen. All you have to do is catch the train.",
    "motif": "🌙"
  },
  {
    "cityId": "roskilde",
    "name": "Kirsten Hovmand",
    "titleDa": "domkirkens murer",
    "titleEn": "cathedral bricklayer",
    "blurbEn": "Kirsten Hovmand has spent twenty-eight years replacing brick in the cathedral that holds forty monarchs, and in all that time the scaffolding has never once come down. She says the only finished things in Roskilde are the five Viking ships in the museum, and they are only finished because they sank.",
    "knewHer": "She came to interpret at a congress here in 2002 and asked to be taken up the scaffolding instead of into the choir. At the top she wanted to know how many years the work had left; when Kirsten told her nobody now on the job would see it finished, she said that was the first good news she had had all week, and went back down to the afternoon session.",
    "greetingDa": "Otte byer og otte hundrede ord bag dig. Nowak nåede seks hundrede. Det skal du ikke sige undskyld for.",
    "greetingEn": "Eight towns and eight hundred words behind you. Nowak reached six hundred. You don't have to apologise for that.",
    "examIntroEn": "A course of brick is only as good as the worst one in it, and I have taken out more of my own work than anyone else’s.",
    "passDa": "Stemplet får du. Stilladset kommer ikke ned i år.",
    "passEn": "You get the stamp. The scaffolding isn't coming down this year.",
    "failDa": "Så river vi muren ned og murer den op igen.",
    "failEn": "Then we take the wall down and lay it again.",
    "farewellDa": "Hun stod deroppe i 2002 og syntes, det var en god nyhed, at vi aldrig bliver færdige. Sig til hende, at vi stadig ikke er det.",
    "farewellEn": "She stood up there in 2002 and thought it good news that we never get finished. Tell her we still aren't.",
    "motif": "🧱"
  },
  {
    "cityId": "kobenhavn",
    "name": "Dorte Winther",
    "titleDa": "hittegodsbestyreren",
    "titleEn": "lost property keeper",
    "blurbEn": "Dorte Winther keeps the police lost property office in Vanløse, out at the end of the metro line — umbrellas, bicycles, hearing aids, a whole shelf of single gloves. She thinks the holding period is far too short, says so at every meeting, and has been quietly ignoring it since about 1992.",
    "knewHer": "They met once, at this counter, in November 1991: she filled in the form for a lost right-hand glove, gave the street and the hour exactly, and asked how long a thing is held before it is disposed of. Six months, Dorte told her. Then I shall write, Ingeborg said — and did, every few years for thirty-five years, and never once came to collect it.",
    "greetingDa": "Så kom du til København. I skabet bag mig ligger der en gammel sag på Nowak, I.M.",
    "greetingEn": "So you made it to Copenhagen. In the cabinet behind me there is an old case on Nowak, I. M.",
    "examIntroEn": "People come to this counter sure they will know the thing when they see it. That is not how it works: you say what it is, and then I go and look.",
    "passDa": "Beskrivelsen passer. Så udleverer vi den.",
    "passEn": "The description matches. Then we hand it over.",
    "failDa": "Så lægger jeg sagen tilbage på hylden, indtil du er klar.",
    "failEn": "Then I put the case back on the shelf until you are ready.",
    "farewellDa": "Tusind ord i passet, og en handske her. Hun bad aldrig om at få den tilbage — hun skrev kun for at høre, om vi stadig havde den. Tag den med hjem til hende.",
    "farewellEn": "A thousand words in the passport, and one glove here. She never asked for it back. She only ever wrote to check that we still had it. Take it home to her.",
    "motif": "🧤"
  }
]

export function championAt(cityIndex: number): Champion {
  const c = CHAMPIONS[cityIndex]
  if (!c) throw new Error(`no champion at index ${cityIndex}`)
  return c
}
