// GENERATED by scripts/make-story.mjs — edit story/story.json instead.
//
// The letter that opens the game: the grandmother, the greatest ClueCabulary
// champion of her era, who learned every language but Danish and is handing the
// unfinished one to her grandchild.

export interface Letter {
  from: string
  fromShort: string
  salutation: string
  body: readonly string[]
  signoff: string
  postscript: string
  tagline: string
}

export const LETTER: Letter = {
  from: "Ingeborg Marta Nowak",
  fromShort: "Farmor",
  salutation: "Kære barnebarn,",
  body: [
  "I have kept a list since I was nineteen. It is in the green ledger in the second drawer, and there is nothing tender about it: a language, the date I began, the date I could read a newspaper in it without help, and one line on what it cost. Forty-one entries. Forty of them closed. The open one is Danish, and it has been open for fifty years.",
  "I began it in April 1976 and got as far as six hundred ord. Then Lisbon, and Portuguese, which came easier and paid better. I opened the Danish entry again twice, in 1989 and in 1996, and both times counted less than I had left there — a sprog you put down does not wait for you, it only goes quiet, the way a house does when nobody lives in it. Four hundred and six, the second time. That is my whole excuse, and fifty years have not improved it. What I kept was one word. I took Farmor out of that language, and it is what you have called me since you could talk, and the only part of Danish that was ever mine.",
  "The plan for finishing survived, because I made it before I knew I would not use it. Ten stops, a hundred ord in each, beginning at the southern border and ending in the capital: Sønderborg, Ribe, Kolding, Aarhus, Viborg, Aalborg, Skagen — where the coast runs out and the road turns back — then Odense, Roskilde, København. A thousand words is not fluency. It is a beginning that can be counted, which is why I chose that number and no other.",
  "In each of the ten there is somebody who knew me. A colleague. A rival. A man in Viborg I beat once at this game, who has been drafting his reply since 1981. I have written to all of them and they have agreed: they will set your rejseprøve when you arrive and put a stempel in your rejsepas when you have earned it, not one word before. I did not choose them for kindness. I chose them because not one of them will lie to you about how you are doing. Ask them about me. They will not agree with each other, and I would rather you had it that way than tidied up by me.",
  "My rejsepas is in the box with this letter, my name at the front in a hand I no longer have. Cross it out and put yours there. Press hard — I have crossed out names before, two of them husbands. Then go south. It is not a long road; it took me fifty years not to drive it. And Danish is not a difficult language, it is a shy one: it swallows half of what it says and assumes you were listening. You will hear havet, the sea, and be certain you misheard. You did not. You will only be the first of us to stand there long enough to be sure."
],
  signoff: "Din, altid,",
  postscript: "They are expecting you. I told them you would be slower than I was and better at it, and I would like at least one of those to turn out wrong.",
  tagline: "Forty languages closed. Danish is still open.",
}
