import { chromium } from 'playwright'
import { spawn } from 'node:child_process'
import { setTimeout as sleep } from 'node:timers/promises'
const BASE = 'http://localhost:4193/ClueCabulary/'
const preview = spawn('npx', ['vite', 'preview', '--port', '4193', '--strictPort'], { cwd: '/home/user/ClueCabulary', stdio: 'ignore' })
await sleep(2500)
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
page.on('pageerror', (e) => console.log('PAGE CRASH:', e.message.split('\n')[0]))
const st = () => page.evaluate(() => JSON.parse(localStorage.getItem('cluecab-journey-v2') ?? '{}').state)
try {
  await page.goto(`${BASE}?mock=1&howto=0&city=9&learned=100&stamps=4`)
  await page.waitForSelector('.city-card')
  console.log('city:', (await page.locator('.city-name').textContent())?.trim())
  await page.click('.btn-gate')
  await page.waitForSelector('.gate-list')
  const n = await page.locator('.gate-item input').count()
  for (let i = 0; i < n; i++) await page.locator('.gate-item input').nth(i).fill('zzz')
  await page.click('.gate-screen .btn-primary')
  await page.waitForSelector('.gate-results')
  const answers = await page.locator('.gate-results .result-answer em').allTextContents()
  await page.click('.gate-actions .btn-primary')
  await page.waitForSelector('.gate-list')
  for (let i = 0; i < n; i++) await page.locator('.gate-item input').nth(i).fill(answers[i].replace(/^\s*=\s*/, '').split(',')[0].trim())
  await page.click('.gate-screen .btn-primary')
  await page.waitForSelector('.gate-results')
  console.log('accepted:', await page.locator('.gate-results .accepted').count(), '/', n)
  console.log('stamps:', JSON.stringify((await st()).stamps))
  console.log('farewell shown?', (await page.locator('.champion-says-farewell').count()) > 0)
  await page.click('.gate-screen .screen-header .icon-btn')   // back arrow, not "Rejsen er slut"
  await page.waitForSelector('.city-card')
  const s = await st()
  console.log('activeExam still set?', s.activeExam !== null, '| gradedAt?', !!s.activeExam?.gradedAt)
  console.log('journey-done shown?', (await page.locator('.journey-done').count()) > 0)
  console.log('resume/abandon buttons:', await page.locator('.exam-resume button').count())
  await page.click('.wotd'); await sleep(300)
  console.log('dictionary opens?', (await page.locator('.sheet').count()) > 0)
  await page.reload(); await page.waitForSelector('.city-card')
  await page.click('.wotd'); await sleep(300)
  console.log('after reload, dictionary opens?', (await page.locator('.sheet').count()) > 0)
  console.log('any route back to the gate screen? gate buttons on home:', await page.locator('.btn-gate').count())
} catch (e) { console.log('ERR', e.message.split('\n')[0]) } finally { await browser.close(); preview.kill() }
