import { chromium } from 'playwright'
import { spawn } from 'node:child_process'
import { setTimeout as sleep } from 'node:timers/promises'
const BASE = 'http://localhost:4195/ClueCabulary/'
const preview = spawn('npx', ['vite', 'preview', '--port', '4195', '--strictPort'], { cwd: '/home/user/ClueCabulary', stdio: 'ignore' })
await sleep(2500)
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
page.on('pageerror', (e) => console.log('PAGE CRASH:', e.message.split('\n')[0]))
const st = () => page.evaluate(() => JSON.parse(localStorage.getItem('cluecab-journey-v2') ?? '{}').state)
try {
  await page.goto(`${BASE}?mock=1&howto=0&city=9&learned=100&stamps=4`)
  await page.waitForSelector('.city-card')
  await page.click('.btn-gate'); await page.waitForSelector('.gate-list')
  const n = await page.locator('.gate-item input').count()
  for (let i = 0; i < n; i++) await page.locator('.gate-item input').nth(i).fill('zzz')
  await page.click('.gate-screen .btn-primary'); await page.waitForSelector('.gate-results')
  const ans = await page.locator('.gate-results .result-answer em').allTextContents()
  await page.click('.gate-actions .btn-primary'); await page.waitForSelector('.gate-list')
  for (let i = 0; i < n; i++) await page.locator('.gate-item input').nth(i).fill(ans[i].replace(/^\s*=\s*/, '').split(',')[0].trim())
  await page.click('.gate-screen .btn-primary'); await page.waitForSelector('.gate-results')
  console.log('passed, stamps:', JSON.stringify((await st()).stamps))
  console.log('farewell shown?', (await page.locator('.champion-says-farewell').count()) > 0)
  // The Android system back gesture / browser back, not the in-app arrow.
  await page.goBack(); await sleep(500)
  await page.waitForSelector('.city-card')
  const s = await st()
  console.log('after system back: activeExam set?', s.activeExam !== null, '| gradedAt?', !!s.activeExam?.gradedAt)
  console.log('journey-done shown?', (await page.locator('.journey-done').count()) > 0)
  console.log('resume/abandon buttons:', await page.locator('.exam-resume button').count())
  console.log('gate buttons on home:', await page.locator('.btn-gate').count())
  await page.click('.wotd'); await sleep(300)
  console.log('dictionary opens?', (await page.locator('.sheet').count()) > 0)
  await page.goto(`${BASE}?mock=1&howto=0`); await page.waitForSelector('.city-card')
  const s2 = await st()
  console.log('after a relaunch: activeExam set?', s2.activeExam !== null)
  await page.click('.wotd'); await sleep(300)
  console.log('dictionary opens?', (await page.locator('.sheet').count()) > 0)
  console.log('collection screen lookups:')
  await page.click('.btn:has-text("Samlingen")'); await page.waitForSelector('.collection-screen')
  await page.locator('.dex-slot').first().click(); await sleep(300)
  console.log('  dictionary opens from the collection?', (await page.locator('.sheet').count()) > 0)
} catch (e) { console.log('ERR', e.message.split('\n')[0]) } finally { await browser.close(); preview.kill() }
