#!/usr/bin/env node
// Turn the authored story JSON into the two typed modules the app imports.
//
//   node scripts/make-story.mjs story/story.json
//
// The JSON is the source of truth for the narrative — one letter and ten city
// champions — and lives under story/ so it can be re-read and revised without
// picking apart a TypeScript file.
import { readFileSync, writeFileSync } from 'node:fs'
import { CITIES } from './cities-order.mjs'

const src = process.argv[2] ?? 'story/story.json'
const story = JSON.parse(readFileSync(src, 'utf8'))

const q = (s) => JSON.stringify(s)

const missing = CITIES.filter((id) => !story.champions.some((c) => c.cityId === id))
if (missing.length) throw new Error(`no champion for: ${missing.join(', ')}`)

const dupes = (key) => {
  const seen = new Map()
  for (const c of story.champions) {
    const v = key(c)
    if (seen.has(v)) return `${seen.get(v)} and ${c.cityId} share ${q(v)}`
    seen.set(v, c.cityId)
  }
  return null
}
// Names collide for a reader long before they collide as strings — Dorthe and
// Dorte are one name spoken aloud — so first names are compared with the
// spelling differences Danish actually tolerates folded away.
const fold = (s) =>
  s
    .toLowerCase()
    .replace(/[øö]/g, 'o')
    .replace(/[æä]/g, 'a')
    .replace(/å/g, 'a')
    .replace(/th/g, 't')
    .replace(/(.)\1/g, '$1')
    .replace(/e$/, '')

for (const [what, key] of [
  ['a name', (c) => c.name],
  ['a first name', (c) => fold(c.name.split(' ')[0])],
  ['a surname', (c) => fold(c.name.split(' ').slice(-1)[0])],
  ['a motif', (c) => c.motif],
  ['a job', (c) => c.titleEn.toLowerCase()],
  ['a trade word', (c) => c.titleEn.toLowerCase().split(' ').slice(-1)[0]],
]) {
  const clash = dupes(key)
  if (clash) throw new Error(`two champions share ${what}: ${clash}`)
}

// The exam screen states the rules directly above whatever the champion says.
for (const c of story.champions) {
  if (/no dictionary|^\s*twenty words\b/i.test(c.examIntroEn)) {
    throw new Error(`${c.cityId} recites the rules the exam screen already states`)
  }
  if (/^the /i.test(c.titleEn)) throw new Error(`${c.cityId}: titleEn should not be definite`)
}

// Ordered by the route, so CHAMPIONS[cityIndex] is the champion of that stop.
const ordered = CITIES.map((id) => story.champions.find((c) => c.cityId === id))

const champions = `// GENERATED by scripts/make-story.mjs — edit story/story.json instead.
//
// The ten people who set the travel exam and stamp the passport. One per city,
// in route order, so CHAMPIONS[cityIndex] is the champion of that stop.

export interface Champion {
  cityId: string
  name: string
  /** Their trade, in Danish. Definite, lower case: "stenhuggeren". */
  titleDa: string
  titleEn: string
  /** Who they are, in a sentence or two. Shown on arrival and on the map. */
  blurbEn: string
  /** How they knew the grandmother. Small and specific. */
  knewHer: string
  greetingDa: string
  greetingEn: string
  /** Shown above the exam paper, in their voice. */
  examIntroEn: string
  passDa: string
  passEn: string
  failDa: string
  failEn: string
  farewellDa: string
  farewellEn: string
  motif: string
}

export const CHAMPIONS: readonly Champion[] = ${JSON.stringify(ordered, null, 2)}

export function championAt(cityIndex: number): Champion {
  const c = CHAMPIONS[cityIndex]
  if (!c) throw new Error(\`no champion at index \${cityIndex}\`)
  return c
}
`

const letter = `// GENERATED by scripts/make-story.mjs — edit story/story.json instead.
//
// The letter that opens the game: the grandmother, the greatest ClueCabulary
// champion of her era, who learned every language but Danish and is handing the
// unfinished one to her grandchild.

export interface Letter {
  from: string
  fromShort: string
  salutation: string
  body: readonly string[]
  signoff: string
  postscript: string
  tagline: string
}

export const LETTER: Letter = {
  from: ${q(story.letter.grandmotherName)},
  fromShort: ${q(story.letter.grandmotherShortName)},
  salutation: ${q(story.letter.salutation)},
  body: ${JSON.stringify(story.letter.body, null, 2)},
  signoff: ${q(story.letter.signoff)},
  postscript: ${q(story.letter.postscript)},
  tagline: ${q(story.letter.tagline)},
}
`

writeFileSync('src/journey/champions.ts', champions)
writeFileSync('src/journey/letter.ts', letter)
console.log(
  `wrote src/journey/champions.ts (${ordered.length} champions) and src/journey/letter.ts`,
)
