/**
 * Generates src/journey/denmark.ts — a small inline SVG path of Denmark's
 * coastline, so the map screen needs no runtime fetch and the PWA stays
 * offline-capable.
 *
 * Source: the official Danish administrative geography (DAGI) regions,
 * published as WGS84 GeoJSON. Fetched once here, projected, simplified with
 * Douglas–Peucker, and committed as generated code.
 *
 *   node scripts/make-map.mjs
 */
import { writeFileSync } from 'node:fs'

const SOURCE =
  'https://raw.githubusercontent.com/Neogeografen/dagi/master/geojson/regioner.geojson'

// Fixed width; the height is derived from the country's true proportions so
// the viewBox hugs the coastline with no dead space.
const WIDTH = 1000
const PADDING = 24
// Rings smaller than this (in projected units²) are dropped — removes the
// hundreds of islets while keeping Bornholm, Als, Samsø, Læsø, Langeland…
const MIN_AREA = 40
// Douglas–Peucker tolerance in projected units. Higher = smaller file.
const TOLERANCE = 1.6
const LAT0 = 56 // mid-Denmark, for the longitude scale factor

const res = await fetch(SOURCE)
if (!res.ok) throw new Error(`fetch failed: ${res.status}`)
const geo = await res.json()

/** Collect every outer ring of every polygon in the file. */
const rings = []
for (const feature of geo.features ?? []) {
  const g = feature.geometry
  if (!g) continue
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.type === 'MultiPolygon' ? g.coordinates : []
  for (const poly of polys) if (poly[0]?.length > 3) rings.push(poly[0])
}
if (rings.length === 0) throw new Error('no rings found — source format changed?')

const allLon = rings.flat().map((p) => p[0])
const allLat = rings.flat().map((p) => p[1])
const lonRange = [Math.min(...allLon), Math.max(...allLon)]
const latRange = [Math.min(...allLat), Math.max(...allLat)]
if (lonRange[0] < 7 || lonRange[1] > 16 || latRange[0] < 54 || latRange[1] > 58.5) {
  throw new Error(
    `coordinates do not look like WGS84 Denmark: lon ${lonRange}, lat ${latRange}`,
  )
}

// Equirectangular projection with the longitude compressed by cos(lat) so the
// country keeps its true proportions.
const kx = Math.cos((LAT0 * Math.PI) / 180)
const rawX = (lon) => lon * kx
const rawY = (lat) => -lat

const xs = allLon.map(rawX)
const ys = allLat.map(rawY)
const minX = Math.min(...xs)
const maxX = Math.max(...xs)
const minY = Math.min(...ys)
const maxY = Math.max(...ys)
const scale = (WIDTH - 2 * PADDING) / (maxX - minX)
const HEIGHT = Math.round((maxY - minY) * scale + 2 * PADDING)
const offsetX = PADDING
const offsetY = PADDING

const project = (lon, lat) => [
  (rawX(lon) - minX) * scale + offsetX,
  (rawY(lat) - minY) * scale + offsetY,
]

/** Shoelace area of a projected ring. */
const areaOf = (pts) => {
  let a = 0
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    a += pts[j][0] * pts[i][1] - pts[i][0] * pts[j][1]
  }
  return Math.abs(a / 2)
}

const perpDist = (p, a, b) => {
  const dx = b[0] - a[0]
  const dy = b[1] - a[1]
  if (dx === 0 && dy === 0) return Math.hypot(p[0] - a[0], p[1] - a[1])
  const t = ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy)
  const cx = a[0] + Math.max(0, Math.min(1, t)) * dx
  const cy = a[1] + Math.max(0, Math.min(1, t)) * dy
  return Math.hypot(p[0] - cx, p[1] - cy)
}

function simplify(points, tolerance) {
  if (points.length < 3) return points
  let maxDist = 0
  let index = 0
  for (let i = 1; i < points.length - 1; i++) {
    const d = perpDist(points[i], points[0], points[points.length - 1])
    if (d > maxDist) {
      maxDist = d
      index = i
    }
  }
  if (maxDist <= tolerance) return [points[0], points[points.length - 1]]
  return [
    ...simplify(points.slice(0, index + 1), tolerance).slice(0, -1),
    ...simplify(points.slice(index), tolerance),
  ]
}

const round = (n) => Math.round(n * 10) / 10

const shapes = rings
  .map((ring) => ring.map(([lon, lat]) => project(lon, lat)))
  .filter((pts) => areaOf(pts) >= MIN_AREA)
  .map((pts) => simplify(pts, TOLERANCE))
  .filter((pts) => pts.length >= 4)
  .sort((a, b) => areaOf(b) - areaOf(a))

const path = shapes
  .map((pts) => `M${pts.map(([x, y]) => `${round(x)} ${round(y)}`).join('L')}Z`)
  .join('')

const out = `// GENERATED by scripts/make-map.mjs — do not edit by hand.
//
// Map data: DAGI (Danmarks Administrative Geografiske Inddeling) — Danish
// public-sector geodata from Geodatastyrelsen & Danske Kommuner, FOT dataset,
// scale 1:500 000. Reprojected equirectangular at lat ${LAT0}° and simplified
// with Douglas–Peucker (tolerance ${TOLERANCE}); the upstream data is unmodified.
// Credit this source wherever the map is shown.

export const MAP_WIDTH = ${WIDTH}
export const MAP_HEIGHT = ${HEIGHT}

/** Place a real coordinate on the same projection as the coastline. */
export function projectCity(lon: number, lat: number): { x: number; y: number } {
  const kx = ${kx}
  const x = (lon * kx - ${minX}) * ${scale} + ${offsetX}
  const y = (-lat - ${minY}) * ${scale} + ${offsetY}
  return { x, y }
}

export const DENMARK_PATH =
  '${path}'
`

writeFileSync(new URL('../src/journey/denmark.ts', import.meta.url), out)

const points = shapes.reduce((n, s) => n + s.length, 0)
console.log(
  `${rings.length} rings -> ${shapes.length} shapes, ${points} points, ` +
    `${(path.length / 1024).toFixed(1)} KB of path data`,
)
